// Auto-generated by generate_nodes_floor1.py
window.NODES_F1 = {

  "SL1_052": {
    image: "SL1_052.jpg",
    label: "SL1_052",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_053", yaw: 79.2, pitch: -0.6 },
      { id: "SL1_054", yaw: 179.2, pitch: -13.6, viewYaw: 180.0, viewPitch: 0.0 },
      { id: "SL1_129", yaw: -0.5, pitch: 1.1 },
      { id: "n25", yaw: 5.8, pitch: -5.5 },
      { id: "SL2_050", yaw: -6.0, pitch: 10.4, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 21.5,
    mapLeft: 16.7,
    hideOnMap: false
  },

  "SL1_053": {
    image: "SL1_053.jpg",
    label: "SL1_053",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_052", yaw: -66.8, pitch: 1.7, viewYaw: 166.2, viewPitch: -4.4 }
    ],
    mapTop: 14.3,
    mapLeft: 16.3,
    hideOnMap: false
  },

  "SL1_054": {
    image: "SL1_054.jpg",
    label: "SL1_054",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_055", yaw: 178.6, pitch: -3.9, viewYaw: 180.0, viewPitch: 0.0 },
      { id: "SL1_052", yaw: -5.7, pitch: -9.2 },
      { id: "SL1_078", yaw: -93.9, pitch: -3.5 }
    ],
    mapTop: 22.2,
    mapLeft: 21.3,
    hideOnMap: false
  },

  "SL1_055": {
    image: "SL1_055.jpg",
    label: "SL1_055",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_054", yaw: 0.8, pitch: -3.4 },
      { id: "SL1_056", yaw: -177.2, pitch: -2.2, viewYaw: 177.3, viewPitch: 0 }
    ],
    mapTop: 23.0,
    mapLeft: 38.0,
    hideOnMap: false
  },

  "SL1_056": {
    image: "SL1_056.jpg",
    label: "SL1_056",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_055", yaw: -4.0, pitch: 2.2 },
      { id: "SL1_058", yaw: 177.3, pitch: -2.5, viewYaw: 180, viewPitch: 0 },
      { id: "SL1_080", yaw: -94.1, pitch: -5.3, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 22.5,
    mapLeft: 50.4,
    hideOnMap: false
  },

  "SL1_057": {
    image: "SL1_057.jpg",
    label: "SL1_057",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [

    ],
    mapTop: 45,
    mapLeft: 35,
    hideOnMap: false
  },

  "SL1_058": {
    image: "SL1_058.jpg",
    label: "SL1_058",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_059", yaw: 173.0, pitch: -2.2, viewYaw: 173.0, viewPitch: -2.2 },
      { id: "SL1_056", yaw: -7.7, pitch: 1.5 }
    ],
    mapTop: 22.0,
    mapLeft: 74.4,
    hideOnMap: false
  },

  "SL1_059": {
    image: "SL1_059.jpg",
    label: "SL1_059",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_058", yaw: -3.0, pitch: 1.8 },
      { id: "SL1_060", yaw: 175.9, pitch: -16.2, viewYaw: 180, viewPitch: 0 },
      { id: "SL1_122", yaw: -93.6, pitch: -8.1, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 22.7,
    mapLeft: 79.6,
    hideOnMap: false
  },

  "SL1_060": {
    image: "SL1_060.jpg",
    label: "SL1_060",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_059", yaw: -4.8, pitch: -0.2 },
      { id: "SL1_061", yaw: 100.3, pitch: -1.1 },
      { id: "SL1_130", yaw: 175.4, pitch: -2.0, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 22.2,
    mapLeft: 84.3,
    hideOnMap: false
  },

  "SL1_061": {
    image: "SL1_061.jpg",
    label: "SL1_061",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_060", yaw: -87.8, pitch: 0.9, viewYaw: -96.6, viewPitch: 4.3 }
    ],
    mapTop: 16.8,
    mapLeft: 84.6,
    hideOnMap: false
  },

  "SL1_062": {
    image: "SL1_062.jpg",
    label: "SL1_062",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_063", yaw: 20, pitch: 0 }
    ],
    mapTop: 50,
    mapLeft: 40,
    hideOnMap: false
  },

  "SL1_063": {
    image: "SL1_063.jpg",
    label: "SL1_063",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_062", yaw: -120, pitch: 0 },
      { id: "SL1_064", yaw: 118.5, pitch: -2.5 },
      { id: "SL1_065", yaw: 178.7, pitch: -12.7, viewYaw: -178.3, viewPitch: -11.9 },
      { id: "SL1_122", yaw: -2.9, pitch: -1.2 }
    ],
    mapTop: 53.8,
    mapLeft: 79.8,
    hideOnMap: false
  },

  "SL1_064": {
    image: "SL1_064.jpg",
    label: "SL1_064",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_063", yaw: 88.5, pitch: -1.0, viewYaw: -86.9, viewPitch: 4.9 }
    ],
    mapTop: 56.8,
    mapLeft: 84.4,
    hideOnMap: false
  },

  "SL1_065": {
    image: "SL1_065.jpg",
    label: "SL1_065",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_066", yaw: -99.1, pitch: -2.1, viewYaw: 180, viewPitch: 3.2 },
      { id: "SL1_063", yaw: 0.5, pitch: -9.2 }
    ],
    mapTop: 64.7,
    mapLeft: 79.1,
    hideOnMap: false
  },

  "SL1_066": {
    image: "SL1_066.jpg",
    label: "SL1_066",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_065", yaw: -3.1, pitch: -1.2 },
      { id: "SL1_068", yaw: 83.3, pitch: -5.4, viewYaw: 87.6, viewPitch: 0.4 },
      { id: "SL1_069", yaw: 178.7, pitch: -8.0, viewYaw: -178.9, viewPitch: -2.3 }
    ],
    mapTop: 64.7,
    mapLeft: 66.9,
    hideOnMap: false
  },

  "SL1_067": {
    image: "SL1_067.jpg",
    label: "SL1_067",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_068", yaw: 76.0, pitch: -10.6, viewYaw: -90, viewPitch: -0.2 }
    ],
    mapTop: 81.5,
    mapLeft: 68.1,
    hideOnMap: false
  },

  "SL1_068": {
    image: "SL1_068.jpg",
    label: "SL1_068",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_067", yaw: 74.3, pitch: -8.7, viewYaw: -107.1, viewPitch: -0.2 },
      { id: "SL1_066", yaw: -111.3, pitch: -12.1, viewYaw: -90, viewPitch: 0 }
    ],
    mapTop: 71.6,
    mapLeft: 66.9,
    hideOnMap: false
  },

  "SL1_069": {
    image: "SL1_069.jpg",
    label: "SL1_069",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_070", yaw: 83.2, pitch: -4.9 },
      { id: "SL1_066", yaw: -3.8, pitch: -4.1 },
      { id: "SL1_071", yaw: 174.9, pitch: -9.5, viewYaw: 174.9, viewPitch: -9.5 }
    ],
    mapTop: 64.9,
    mapLeft: 58.7,
    hideOnMap: false
  },

  "SL1_070": {
    image: "SL1_070.jpg",
    label: "SL1_070",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_069", yaw: -120, pitch: 0 },
      { id: "SL1_131", yaw: 69.7, pitch: -1.5, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 80.5,
    mapLeft: 60.0,
    hideOnMap: false
  },

  "SL1_071": {
    image: "SL1_071.jpg",
    label: "SL1_071",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_072", yaw: 176.0, pitch: -5.5, viewYaw: -179.8, viewPitch: -0.1 },
      { id: "SL1_069", yaw: -2.8, pitch: -5.5 },
      { id: "SL1_081", yaw: -95.9, pitch: -5.0 }
    ],
    mapTop: 63.4,
    mapLeft: 50.0,
    hideOnMap: false
  },

  "SL1_072": {
    image: "SL1_072.jpg",
    label: "SL1_072",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_071", yaw: -2.5, pitch: -0.5, viewYaw: -2.5, viewPitch: -0.5 },
      { id: "SL1_073", yaw: -179.0, pitch: -8.0, viewYaw: -179.0, viewPitch: -8.0 }
    ],
    mapTop: 64.9,
    mapLeft: 30.0,
    hideOnMap: false
  },

  "SL1_073": {
    image: "SL1_073.jpg",
    label: "SL1_073",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_072", yaw: -3.2, pitch: -2.5 },
      { id: "SL1_074", yaw: -88.6, pitch: -3.8, viewYaw: 180, viewPitch: 0 },
      { id: "SL1_113", yaw: -134.9, pitch: -18.5, viewYaw: 180, viewPitch: 0 },
      { id: "SL1_115", yaw: -177.4, pitch: -2.7, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 64.7,
    mapLeft: 21.3,
    hideOnMap: false
  },

  "SL1_074": {
    image: "SL1_074.jpg",
    label: "SL1_074",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_073", yaw: -1.7, pitch: -14.6, viewYaw: 90, viewPitch: 0 },
      { id: "SL1_075", yaw: 101.3, pitch: -0.9, viewYaw: -90, viewPitch: 0 },
      { id: "SL1_078", yaw: 177.3, pitch: -7.4, viewYaw: 177.3, viewPitch: -7.4 }
    ],
    mapTop: 50.6,
    mapLeft: 20.7,
    hideOnMap: false
  },

  "SL1_075": {
    image: "SL1_075.jpg",
    label: "SL1_075",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_074", yaw: -68.3, pitch: 1.2, viewYaw: -90, viewPitch: 0 },
      { id: "SL1_076", yaw: 136.2, pitch: -0.6 }
    ],
    mapTop: 54.8,
    mapLeft: 14.3,
    hideOnMap: false
  },

  "SL1_076": {
    image: "SL1_076.jpg",
    label: "SL1_076",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_075", yaw: 152.4, pitch: -6.9 }
    ],
    mapTop: 57.8,
    mapLeft: 10.9,
    hideOnMap: false
  },

  "SL1_077": {
    image: "SL1_077.jpg",
    label: "SL1_077",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [

    ],
    mapTop: 65,
    mapLeft: 55,
    hideOnMap: true
  },

  "SL1_078": {
    image: "SL1_078.jpg",
    label: "SL1_078",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_079", yaw: 83.2, pitch: -10.0, viewYaw: -175.4, viewPitch: 1.4 },
      { id: "SL1_074", yaw: -3.3, pitch: -3.8 },
      { id: "SL1_054", yaw: 179.5, pitch: -5.4, viewYaw: 90, viewPitch: -4.7 }
    ],
    mapTop: 41.5,
    mapLeft: 21.5,
    hideOnMap: false
  },

  "SL1_079": {
    image: "SL1_079.jpg",
    label: "SL1_079",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_078", yaw: -3.6, pitch: -4.0, viewYaw: -90, viewPitch: -4.0 }
    ],
    mapTop: 44.9,
    mapLeft: 14.4,
    hideOnMap: false
  },

  "SL1_080": {
    image: "SL1_080.jpg",
    label: "SL1_080",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_081", yaw: -178.1, pitch: -4.7, viewYaw: 175.5, viewPitch: -0.8 },
      { id: "SL1_056", yaw: -1.1, pitch: -1.8, viewYaw: 90, viewPitch: 0 }
    ],
    mapTop: 36.6,
    mapLeft: 50.6,
    hideOnMap: false
  },

  "SL1_081": {
    image: "SL1_081.jpg",
    label: "SL1_081",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_080", yaw: 3.5, pitch: -4.0 },
      { id: "SL1_071", yaw: -176.1, pitch: -6.8, viewYaw: 90, viewPitch: 0.5 }
    ],
    mapTop: 55.3,
    mapLeft: 50.2,
    hideOnMap: false
  },

  "SL1_113": {
    image: "SL1_113.jpg",
    label: "SL1_113",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_073", yaw: 92.1, pitch: -22.3, viewYaw: 90, viewPitch: 0 },
      { id: "n20", yaw: 172.3, pitch: -26.4 }
    ],
    mapTop: 61.2,
    mapLeft: 18.5,
    hideOnMap: false
  },

  "SL1_115": {
    image: "SL1_115.jpg",
    label: "SL1_115",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_073", yaw: 6.0, pitch: -0.1 },
      { id: "SL1_124", yaw: -169.2, pitch: -1.9 }
    ],
    mapTop: 65.2,
    mapLeft: 10.9,
    hideOnMap: false
  },

  "SL1_122": {
    image: "SL1_122.jpg",
    label: "SL1_122",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_123", yaw: 94.4, pitch: -5.6 },
      { id: "SL1_059", yaw: -6.4, pitch: -3.8, viewYaw: 90, viewPitch: 0 },
      { id: "SL1_063", yaw: 173.0, pitch: -4.9, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 34.6,
    mapLeft: 79.8,
    hideOnMap: false
  },

  "SL1_123": {
    image: "SL1_123.jpg",
    label: "SL1_123",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_122", yaw: -88.5, pitch: -1.5, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 33.6,
    mapLeft: 85.0,
    hideOnMap: false
  },

  "SL1_124": {
    image: "SL1_124.jpg",
    label: "SL1_124",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_125", yaw: 86.9, pitch: -4.5, viewYaw: -179, viewPitch: 0 },
      { id: "SL1_115", yaw: 177.9, pitch: -2.8 },
      { id: "SL1_126", yaw: -93.4, pitch: -5.2, viewYaw: -150, viewPitch: 4 }
    ],
    mapTop: 74,
    mapLeft: 64,
    hideOnMap: true
  },

  "SL1_125": {
    image: "SL1_125.jpg",
    label: "SL1_125",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_124", yaw: -15.5, pitch: -1.4 }
    ],
    mapTop: 75,
    mapLeft: 65,
    hideOnMap: true
  },

  "SL1_126": {
    image: "SL1_126.jpg",
    label: "SL1_126",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_124", yaw: -7.4, pitch: -0.6 }
    ],
    mapTop: 76,
    mapLeft: 66,
    hideOnMap: true
  },

  "SL1_127": {
    image: "SL1_127.jpg",
    label: "SL1_127",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_130", yaw: 55.9, pitch: 2.9, viewYaw: 90, viewPitch: 0 }
    ],
    mapTop: 77,
    mapLeft: 67,
    hideOnMap: true
  },

  "SL1_128": {
    image: "SL1_128.jpg",
    label: "SL1_128",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_130", yaw: -41.2, pitch: 3.1, viewYaw: -90, viewPitch: 0 }
    ],
    mapTop: 78,
    mapLeft: 68,
    hideOnMap: true
  },

  "SL1_129": {
    image: "SL1_129.jpg",
    label: "SL1_129",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_052", yaw: -174.9, pitch: -0.5 }
    ],
    mapTop: 14.3,
    mapLeft: 4.2,
    hideOnMap: false
  },

  "SL1_130": {
    image: "SL1_130.jpg",
    label: "SL1_130",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_060", yaw: 0.4, pitch: 1.9 },
      { id: "SL1_127", yaw: -90.9, pitch: -1.4, viewYaw: 180.0, viewPitch: 1.0 },
      { id: "SL1_128", yaw: 81.4, pitch: -1.2, viewYaw: 180, viewPitch: 0 },
      { id: "n1", yaw: -179.5, pitch: -13.1, viewYaw: 0, viewPitch: 0 },
      { id: "SL2_048", yaw: 169.6, pitch: 9.8 }
    ],
    mapTop: 23.1,
    mapLeft: 93.7,
    hideOnMap: false
  },

  "SL1_131": {
    image: "SL1_131.jpg",
    label: "SL1_131",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_132", yaw: 166.1, pitch: 12.7 },
      { id: "SL1_070", yaw: 86.5, pitch: -0.6 },
      { id: "n27", yaw: -176.4, pitch: -19.4 }
    ],
    mapTop: 91.3,
    mapLeft: 63.1,
    hideOnMap: false
  },

  "SL1_132": {
    image: "SL1_132.jpg",
    label: "SL1_132",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL1_131", yaw: 6.0, pitch: -21.9 },
      { id: "SL2_051", yaw: -11.9, pitch: 20.2 }
    ],
    mapTop: 91.3,
    mapLeft: 68.5,
    hideOnMap: false
  },

};
