// Auto-generated by generate_nodes_floor3.py
window.NODES_F3 = {

  "SL3_003": {
    image: "SL3_003.jpg",
    label: "SL3_003",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_004", yaw: -177.2, pitch: -6.5, viewYaw: 180, viewPitch: 0 },
      { id: "SL3_107", yaw: 20, pitch: 0, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 19.9,
    mapLeft: 15.7,
    hideOnMap: false
  },

  "SL3_004": {
    image: "SL3_004.jpg",
    label: "SL3_004",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_003", yaw: -2.9, pitch: -5.6 },
      { id: "SL3_019", yaw: -92.3, pitch: -5.0 },
      { id: "SL3_020", yaw: 177.5, pitch: -6.7, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 19.6,
    mapLeft: 23.9,
    hideOnMap: false
  },

  "SL3_005": {
    image: "SL3_005.jpg",
    label: "SL3_005",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_014", yaw: -92.7, pitch: -7.3 },
      { id: "SL3_020", yaw: -3.5, pitch: -0.0 },
      { id: "SL3_021", yaw: 177.3, pitch: -6.7, viewYaw: 177.9, viewPitch: -4.2 }
    ],
    mapTop: 20.4,
    mapLeft: 49.6,
    hideOnMap: false
  },

  "SL3_006": {
    image: "SL3_006.jpg",
    label: "SL3_006",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_007", yaw: -89.3, pitch: -1.5, viewYaw: -180, viewPitch: 0 },
      { id: "SL3_021", yaw: 1.7, pitch: -2.8 },
      { id: "SL3_109", yaw: -177.6, pitch: -4.8, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 20.1,
    mapLeft: 75.4,
    hideOnMap: false
  },

  "SL3_007": {
    image: "SL3_007.jpg",
    label: "SL3_007",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_006", yaw: -0.2, pitch: -3.8, viewYaw: 90, viewPitch: 0 },
      { id: "SL3_008", yaw: 179.5, pitch: -6.0, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 31.6,
    mapLeft: 75.9,
    hideOnMap: false
  },

  "SL3_008": {
    image: "SL3_008.jpg",
    label: "SL3_008",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_007", yaw: -2.7, pitch: -0.5 },
      { id: "SL3_009", yaw: 179.0, pitch: -5.0, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 48.1,
    mapLeft: 75.6,
    hideOnMap: false
  },

  "SL3_009": {
    image: "SL3_009.jpg",
    label: "SL3_009",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_008", yaw: 6.9, pitch: -6.2 },
      { id: "SL3_010", yaw: -90.6, pitch: -4.7, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 62.8,
    mapLeft: 75.4,
    hideOnMap: false
  },

  "SL3_010": {
    image: "SL3_010.jpg",
    label: "SL3_010",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_009", yaw: -2.4, pitch: -1.7, viewYaw: 90, viewPitch: 0 },
      { id: "SL3_011", yaw: 176.1, pitch: -8.2, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 63.7,
    mapLeft: 62.8,
    hideOnMap: false
  },

  "SL3_011": {
    image: "SL3_011.jpg",
    label: "SL3_011",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_010", yaw: -3.2, pitch: 0.1, viewYaw: 0, viewPitch: 0 },
      { id: "SL3_012", yaw: 175.6, pitch: -4.4, viewYaw: 180, viewPitch: 0 },
      { id: "SL3_106", yaw: 88.4, pitch: -1.4 }
    ],
    mapTop: 63.7,
    mapLeft: 55.9,
    hideOnMap: false
  },

  "SL3_012": {
    image: "SL3_012.jpg",
    label: "SL3_012",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_011", yaw: 9.2, pitch: -5.4 },
      { id: "SL3_013", yaw: -83.5, pitch: -5.0, viewYaw: 180, viewPitch: 0 },
      { id: "SL3_015", yaw: -172.6, pitch: -6.0, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 63.4,
    mapLeft: 49.3,
    hideOnMap: false
  },

  "SL3_013": {
    image: "SL3_013.jpg",
    label: "SL3_013",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_012", yaw: 1.4, pitch: -3.9, viewYaw: 90, viewPitch: -3.9 },
      { id: "SL3_014", yaw: -177.1, pitch: -3.6, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 50.4,
    mapLeft: 49.4,
    hideOnMap: false
  },

  "SL3_014": {
    image: "SL3_014.jpg",
    label: "SL3_014",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_013", yaw: 3.0, pitch: 1.0 },
      { id: "SL3_005", yaw: -175.7, pitch: -10.4, viewYaw: 90, viewPitch: 0 }
    ],
    mapTop: 33.7,
    mapLeft: 49.4,
    hideOnMap: false
  },

  "SL3_015": {
    image: "SL3_015.jpg",
    label: "SL3_015",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_016", yaw: -171.2, pitch: -5.4, viewYaw: 180, viewPitch: 0 },
      { id: "SL3_012", yaw: 7.6, pitch: -1.9 }
    ],
    mapTop: 63.1,
    mapLeft: 37.2,
    hideOnMap: false
  },

  "SL3_016": {
    image: "SL3_016.jpg",
    label: "SL3_016",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_015", yaw: 4.5, pitch: -0.4 },
      { id: "SL3_017", yaw: -86.1, pitch: -10.4, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 62.5,
    mapLeft: 23.5,
    hideOnMap: false
  },

  "SL3_017": {
    image: "SL3_017.jpg",
    label: "SL3_017",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_016", yaw: 0.2, pitch: -4.8 },
      { id: "SL3_018", yaw: 45.5, pitch: -17.1 },
      { id: "SL3_019", yaw: -178.3, pitch: -5.1, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 57.5,
    mapLeft: 23.0,
    hideOnMap: false
  },

  "SL3_018": {
    image: "SL3_018.jpg",
    label: "SL3_018",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_017", yaw: -40.8, pitch: -8.9, viewYaw: -90, viewPitch: 0 }
    ],
    mapTop: 56.3,
    mapLeft: 18.3,
    hideOnMap: false
  },

  "SL3_019": {
    image: "SL3_019.jpg",
    label: "SL3_019",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_017", yaw: -3.2, pitch: -3.5 },
      { id: "SL3_004", yaw: 177.1, pitch: -8.2, viewYaw: 90, viewPitch: 0 }
    ],
    mapTop: 36.0,
    mapLeft: 23.5,
    hideOnMap: false
  },

  "SL3_020": {
    image: "SL3_020.jpg",
    label: "SL3_020",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_004", yaw: -4.1, pitch: -2.0 },
      { id: "SL3_005", yaw: 175.6, pitch: -4.2, viewYaw: 177.9, viewPitch: -4.2 }
    ],
    mapTop: 20.4,
    mapLeft: 35.2,
    hideOnMap: false
  },

  "SL3_021": {
    image: "SL3_021.jpg",
    label: "SL3_021",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_005", yaw: -5.2, pitch: -4.5 },
      { id: "SL3_006", yaw: 175.8, pitch: -4.7, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 20.1,
    mapLeft: 62.4,
    hideOnMap: false
  },

  "SL3_106": {
    image: "SL3_106.jpg",
    label: "SL3_106",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_011", yaw: 74.6, pitch: -0.5, viewYaw: -90, viewPitch: 0 },
      { id: "SL3_111", yaw: -115.5, pitch: -2.1, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 79.6,
    mapLeft: 58.5,
    hideOnMap: false
  },

  "SL3_107": {
    image: "SL3_107.jpg",
    label: "SL3_107",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_108", yaw: 166.6, pitch: -25.0, viewYaw: 180, viewPitch: 0 },
      { id: "SL3_003", yaw: -6.1, pitch: 0.4, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 19.9,
    mapLeft: 11.5,
    hideOnMap: false
  },

  "SL3_108": {
    image: "SL3_108.jpg",
    label: "SL3_108",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_107", yaw: 1.1, pitch: 18.8 },
      { id: "SL2_049", yaw: -7.5, pitch: -21.6 }
    ],
    mapTop: 18.7,
    mapLeft: 3.3,
    hideOnMap: false
  },

  "SL3_109": {
    image: "SL3_109.jpg",
    label: "SL3_109",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_110", yaw: -178.9, pitch: -23.2, viewYaw: -150, viewPitch: 0 },
      { id: "SL3_006", yaw: 2.0, pitch: -0.1 }
    ],
    mapTop: 21.3,
    mapLeft: 88.5,
    hideOnMap: false
  },

  "SL3_110": {
    image: "SL3_110.jpg",
    label: "SL3_110",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_109", yaw: 10.3, pitch: 18.2 },
      { id: "SL2_047", yaw: 23.8, pitch: -21.6, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 20.2,
    mapLeft: 95.1,
    hideOnMap: false
  },

  "SL3_111": {
    image: "SL3_111.jpg",
    label: "SL3_111",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL3_106", yaw: 97.2, pitch: -1.3, viewYaw: 90, viewPitch: 0 },
      { id: "SL2_052", yaw: -175.8, pitch: -24.2 }
    ],
    mapTop: 89.0,
    mapLeft: 61.2,
    hideOnMap: false
  }

};
