// Auto-generated by generate_nodes_floor2.py
window.NODES_F2 = {

  "SL2_026": {
    image: "SL2_026.jpg",
    label: "SL2_026",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_047", yaw: 1.3, pitch: 2.0 }
    ],
    mapTop: 40,
    mapLeft: 30,
    hideOnMap: false
  },

  "SL2_027": {
    image: "SL2_027.jpg",
    label: "SL2_027",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_028", yaw: -178.5, pitch: -12.8, viewYaw: 180, viewPitch: 0 },
      { id: "SL2_047", yaw: -1.1, pitch: 2.7 }
    ],
    mapTop: 29.1,
    mapLeft: 88.5,
    hideOnMap: false
  },

  "SL2_028": {
    image: "SL2_028.jpg",
    label: "SL2_028",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_027", yaw: -2.2, pitch: -9.4 },
      { id: "SL2_029", yaw: 180.0, pitch: -4.3, viewYaw: 179.1, viewPitch: 0.5 },
      { id: "SL2_046", yaw: 88.3, pitch: -1.3 }
    ],
    mapTop: 29.1,
    mapLeft: 82.8,
    hideOnMap: false
  },

  "SL2_029": {
    image: "SL2_029.jpg",
    label: "SL2_029",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_028", yaw: -5.1, pitch: 0.4 },
      { id: "SL2_030", yaw: 175.6, pitch: -3.0, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 30.1,
    mapLeft: 73.3,
    hideOnMap: false
  },

  "SL2_030": {
    image: "SL2_030.jpg",
    label: "SL2_030",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_029", yaw: -0.8, pitch: 0.4 },
      { id: "SL2_031", yaw: 89.2, pitch: -4.3 },
      { id: "SL2_032", yaw: 179.2, pitch: -7.4, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 30.4,
    mapLeft: 59.8,
    hideOnMap: false
  },

  "SL2_031": {
    image: "SL2_031.jpg",
    label: "SL2_031",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_030", yaw: -47.0, pitch: 3.4, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 38.3,
    mapLeft: 57.2,
    hideOnMap: false
  },

  "SL2_032": {
    image: "SL2_032.jpg",
    label: "SL2_032",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_033", yaw: 84.5, pitch: -0.3, viewYaw: 180, viewPitch: 0 },
      { id: "SL2_030", yaw: -4.9, pitch: -3.0 },
      { id: "SL2_035", yaw: 175.4, pitch: -1.8, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 29.9,
    mapLeft: 52.2,
    hideOnMap: false
  },

  "SL2_033": {
    image: "SL2_033.jpg",
    label: "SL2_033",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_032", yaw: -8.2, pitch: 1.1, viewYaw: -90, viewPitch: 0 },
      { id: "SL2_034", yaw: 172.3, pitch: -9.7, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 43.0,
    mapLeft: 51.5,
    hideOnMap: false
  },

  "SL2_034": {
    image: "SL2_034.jpg",
    label: "SL2_034",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_033", yaw: -4.6, pitch: 0.2 },
      { id: "SL2_038", yaw: 177.3, pitch: -7.5, viewYaw: 90, viewPitch: 0 }
    ],
    mapTop: 62.5,
    mapLeft: 52.4,
    hideOnMap: false
  },

  "SL2_035": {
    image: "SL2_035.jpg",
    label: "SL2_035",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_036", yaw: 173.3, pitch: -2.6, viewYaw: -180, viewPitch: 0 },
      { id: "SL2_032", yaw: -4.9, pitch: -3.0 }
    ],
    mapTop: 30.9,
    mapLeft: 29.1,
    hideOnMap: false
  },

  "SL2_036": {
    image: "SL2_036.jpg",
    label: "SL2_036",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_035", yaw: -5.4, pitch: 0.6 },
      { id: "SL2_037", yaw: -98.6, pitch: -4.0, viewYaw: -180, viewPitch: 0 },
      { id: "SL2_049", yaw: 177.4, pitch: -1.1, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 30.1,
    mapLeft: 16.1,
    hideOnMap: false
  },

  "SL2_037": {
    image: "SL2_037.jpg",
    label: "SL2_037",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_036", yaw: -100.8, pitch: 0.6, viewYaw: 90, viewPitch: 0 }
    ],
    mapTop: 24.5,
    mapLeft: 19.6,
    hideOnMap: false
  },

  "SL2_038": {
    image: "SL2_038.jpg",
    label: "SL2_038",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_039", yaw: -1.6, pitch: 2.5 },
      { id: "SL2_034", yaw: -93.3, pitch: -0.3 }
    ],
    mapTop: 72.2,
    mapLeft: 52.4,
    hideOnMap: false
  },

  "SL2_039": {
    image: "SL2_039.jpg",
    label: "SL2_039",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_038", yaw: 175.0, pitch: -8.1, viewYaw: 180, viewPitch: 0 },
      { id: "SL2_044", yaw: -3.8, pitch: -0.3, viewYaw: -90, viewPitch: 0 },
      { id: "SL2_051", yaw: 82.4, pitch: -0.2, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 72.7,
    mapLeft: 67.5,
    hideOnMap: false
  },

  "SL2_044": {
    image: "SL2_044.jpg",
    label: "SL2_044",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_039", yaw: 81.2, pitch: -1.0, viewYaw: 180, viewPitch: 0 },
      { id: "SL2_045", yaw: 174.8, pitch: -2.8, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 72.2,
    mapLeft: 81.5,
    hideOnMap: false
  },

  "SL2_045": {
    image: "SL2_045.jpg",
    label: "SL2_045",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_044", yaw: -1.4, pitch: -2.9 },
      { id: "SL2_046", yaw: 178.9, pitch: -4.2, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 56.9,
    mapLeft: 82.9,
    hideOnMap: false
  },

  "SL2_046": {
    image: "SL2_046.jpg",
    label: "SL2_046",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_045", yaw: -1.8, pitch: 1.2 },
      { id: "SL2_028", yaw: 178.9, pitch: -4.2, viewYaw: -90, viewPitch: 0 }
    ],
    mapTop: 40.2,
    mapLeft: 82.5,
    hideOnMap: false
  },

  "SL2_047": {
    image: "SL2_047.jpg",
    label: "SL2_047",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_048", yaw: 5.4, pitch: -19.4 },
      { id: "SL2_027", yaw: -176.8, pitch: -2.3, viewYaw: -180, viewPitch: 0 },
      { id: "SL2_026", yaw: -63.0, pitch: -7.8, viewYaw: -180, viewPitch: 0 },
      { id: "SL3_110", yaw: -5.4, pitch: 16.7, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 28.4,
    mapLeft: 95.6,
    hideOnMap: false
  },

  "SL2_048": {
    image: "SL2_048.jpg",
    label: "SL2_048",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_047", yaw: 165.8, pitch: 12.9, viewYaw: 180, viewPitch: 0 },
      { id: "SL1_130", yaw: -173.9, pitch: -28.5 }
    ],
    mapTop: 28.7,
    mapLeft: 97.2,
    hideOnMap: false
  },

  "SL2_049": {
    image: "SL2_049.jpg",
    label: "SL2_049",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_050", yaw: 173.1, pitch: -19.9, viewYaw: 180, viewPitch: 0 },
      { id: "SL2_036", yaw: -5.5, pitch: 3.5 },
      { id: "SL3_108", yaw: -174.7, pitch: 10.9, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 30.9,
    mapLeft: 8.7,
    hideOnMap: false
  },

  "SL2_050": {
    image: "SL2_050.jpg",
    label: "SL2_050",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_049", yaw: -4.9, pitch: 18.2 },
      { id: "SL1_052", yaw: -24.3, pitch: -25.7 }
    ],
    mapTop: 31.9,
    mapLeft: 5.2,
    hideOnMap: false
  },

  "SL2_051": {
    image: "SL2_051.jpg",
    label: "SL2_051",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_052", yaw: 175.9, pitch: 13.5 },
      { id: "SL2_039", yaw: 96.8, pitch: -1.2, viewYaw: 96.8, viewPitch: -1.2 },
      { id: "SL1_132", yaw: -168.5, pitch: -24.2, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 96.3,
    mapLeft: 66.1,
    hideOnMap: false
  },

  "SL2_052": {
    image: "SL2_052.jpg",
    label: "SL2_052",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "SL2_051", yaw: -120, pitch: 0 },
      { id: "SL3_111", yaw: 166.6, pitch: 15.0 }
    ],
    mapTop: 97.0,
    mapLeft: 69.6,
    hideOnMap: false
  }

};
