// Auto-generated by generate_nodes_js.py
window.NODES = {

  n1: {
    image: "SL0_084.jpg",
    label: "Image 1",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n2", yaw: 20, pitch: 0 }
    ],
    mapTop: 40,
    mapLeft: 30
  },

  n2: {
    image: "SL0_085.jpg",
    label: "Image 2",
    description: "",
    defaultYaw: 178.1,
    defaultPitch: 22.8,
    neighbors: [
      { id: "n1", yaw: -120, pitch: 0, viewYaw: -10.6, viewPitch: 11.1 },
      { id: "n3", yaw: 20, pitch: 0, viewYaw: 178.1, viewPitch: 22.8 }
    ],
    mapTop: 41,
    mapLeft: 31
  },

  n3: {
    image: "SL0_086.jpg",
    label: "Image 3",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n2", yaw: -120, pitch: 0 },
      { id: "n4", yaw: 20, pitch: 0 }
    ],
    mapTop: 42,
    mapLeft: 32
  },

  n4: {
    image: "SL0_087.jpg",
    label: "Image 4",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n3", yaw: -120, pitch: 0 },
      { id: "n5", yaw: 20, pitch: 0 }
    ],
    mapTop: 43,
    mapLeft: 33
  },

  n5: {
    image: "SL0_088.jpg",
    label: "Image 5",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n4", yaw: -120, pitch: 0 },
      { id: "n6", yaw: 20, pitch: 0 }
    ],
    mapTop: 44,
    mapLeft: 34
  },

  n6: {
    image: "SL0_089.jpg",
    label: "Image 6",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n5", yaw: -120, pitch: 0 },
      { id: "n7", yaw: 20, pitch: 0 }
    ],
    mapTop: 45,
    mapLeft: 35
  },

  n7: {
    image: "SL0_090.jpg",
    label: "Image 7",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n6", yaw: -120, pitch: 0 },
      { id: "n8", yaw: 20, pitch: 0 }
    ],
    mapTop: 46,
    mapLeft: 36
  },

  n8: {
    image: "SL0_091.jpg",
    label: "Image 8",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n7", yaw: -120, pitch: 0 },
      { id: "n9", yaw: 20, pitch: 0 }
    ],
    mapTop: 47,
    mapLeft: 37
  },

  n9: {
    image: "SL0_092.jpg",
    label: "Image 9",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n8", yaw: -120, pitch: 0 },
      { id: "n10", yaw: 20, pitch: 0 }
    ],
    mapTop: 48,
    mapLeft: 38
  },

  n10: {
    image: "SL0_093.jpg",
    label: "Image 10",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n9", yaw: -120, pitch: 0 },
      { id: "n11", yaw: 20, pitch: 0 }
    ],
    mapTop: 49,
    mapLeft: 39
  },

  n11: {
    image: "SL0_094.jpg",
    label: "Image 11",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n10", yaw: -120, pitch: 0 },
      { id: "n12", yaw: 20, pitch: 0 }
    ],
    mapTop: 50,
    mapLeft: 40
  },

  n12: {
    image: "SL0_095.jpg",
    label: "Image 12",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n11", yaw: -120, pitch: 0 },
      { id: "n13", yaw: 20, pitch: 0 }
    ],
    mapTop: 51,
    mapLeft: 41
  },

  n13: {
    image: "SL0_096.jpg",
    label: "Image 13",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n12", yaw: -120, pitch: 0 },
      { id: "n14", yaw: 20, pitch: 0 }
    ],
    mapTop: 52,
    mapLeft: 42
  },

  n14: {
    image: "SL0_097.jpg",
    label: "Image 14",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n13", yaw: -120, pitch: 0 },
      { id: "n15", yaw: 20, pitch: 0 }
    ],
    mapTop: 53,
    mapLeft: 43
  },

  n15: {
    image: "SL0_098.jpg",
    label: "Image 15",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n14", yaw: -120, pitch: 0 },
      { id: "n16", yaw: 20, pitch: 0 }
    ],
    mapTop: 54,
    mapLeft: 44
  },

  n16: {
    image: "SL0_107.jpg",
    label: "Image 16",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n15", yaw: -120, pitch: 0 },
      { id: "n17", yaw: 20, pitch: 0 }
    ],
    mapTop: 55,
    mapLeft: 45
  },

  n17: {
    image: "SL0_108.jpg",
    label: "Image 17",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n16", yaw: -120, pitch: 0 },
      { id: "n18", yaw: 20, pitch: 0 }
    ],
    mapTop: 56,
    mapLeft: 46
  },

  n18: {
    image: "SL0_109.jpg",
    label: "Image 18",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n17", yaw: -120, pitch: 0 },
      { id: "n19", yaw: 20, pitch: 0 }
    ],
    mapTop: 57,
    mapLeft: 47
  },

  n19: {
    image: "SL0_111.jpg",
    label: "Image 19",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n18", yaw: -120, pitch: 0 },
      { id: "n20", yaw: 20, pitch: 0 }
    ],
    mapTop: 58,
    mapLeft: 48
  },

  n20: {
    image: "SL0_112.jpg",
    label: "Image 20",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n19", yaw: -120, pitch: 0 },
      { id: "n21", yaw: 20, pitch: 0 }
    ],
    mapTop: 59,
    mapLeft: 49
  },

  n21: {
    image: "SL0_123.jpg",
    label: "Image 21",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n20", yaw: -120, pitch: 0 },
      { id: "n22", yaw: 20, pitch: 0 }
    ],
    mapTop: 60,
    mapLeft: 50
  },

  n22: {
    image: "SL0_124.jpg",
    label: "Image 22",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n21", yaw: -120, pitch: 0 },
      { id: "n23", yaw: 20, pitch: 0 }
    ],
    mapTop: 61,
    mapLeft: 51
  },

  n23: {
    image: "SL0_125.jpg",
    label: "Image 23",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n22", yaw: -120, pitch: 0 },
      { id: "n24", yaw: 20, pitch: 0 }
    ],
    mapTop: 62,
    mapLeft: 52
  },

  n24: {
    image: "SL0_126.jpg",
    label: "Image 24",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n23", yaw: -120, pitch: 0 },
      { id: "n25", yaw: 20, pitch: 0 }
    ],
    mapTop: 63,
    mapLeft: 53
  },

  n25: {
    image: "SL0_127.jpg",
    label: "Image 25",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n24", yaw: -120, pitch: 0 }
    ],
    mapTop: 64,
    mapLeft: 54
  }

};
