// Auto-generated by generate_nodes_floor0.py
window.NODES_F0 = {

  n1: {
    image: "SL0_084.jpg",
    label: "Image 1",
    description: "",
    defaultYaw: 180,
    defaultPitch: 0,
    neighbors: [
      { id: "n2", yaw: -178, pitch: -22, viewYaw: 180, viewPitch: 0 },
      { id: "SL1_130", yaw: 173.8, pitch: 8.7 }
    ],
    mapTop: 19.5,
    mapLeft: 95.7,
    hideOnMap: false
  },

  n2: {
    image: "SL0_085.jpg",
    label: "Image 2",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n1", yaw: -12, pitch: 26.9, viewYaw: 0, viewPitch: 0 },
      { id: "n3", yaw: -180, pitch: 0, viewYaw: 180.0, viewPitch: 0 }
    ],
    mapTop: 19.5,
    mapLeft: 90.4,
    hideOnMap: false
  },

  n3: {
    image: "SL0_086.jpg",
    label: "Image 3",
    description: "",
    defaultYaw: 180.0,
    defaultPitch: 0.0,
    neighbors: [
      { id: "n2", yaw: -1.0, pitch: 4, viewYaw: 0, viewPitch: 0 },
      { id: "n4", yaw: 178, pitch: -8, viewYaw: -180, viewPitch: 0 }
    ],
    mapTop: 19.2,
    mapLeft: 79.4,
    hideOnMap: false
  },

  n4: {
    image: "SL0_087.jpg",
    label: "Image 4",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n3", yaw: -4, pitch: -4, viewYaw: 0, viewPitch: 0 },
      { id: "n5", yaw: 177, pitch: -8, viewYaw: 180, viewPitch: 0 },
      { id: "n17", yaw: 88, pitch: -5, viewYaw: -10, viewPitch: 7.6 }
    ],
    mapTop: 19.2,
    mapLeft: 71.5,
    hideOnMap: false
  },

  n5: {
    image: "SL0_088.jpg",
    label: "Image 5",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n4", yaw: -1, pitch: -5 },
      { id: "n6", yaw: -65, pitch: -2 },
      { id: "n7", yaw: 180, pitch: -8, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 19.8,
    mapLeft: 66.7,
    hideOnMap: false
  },

  n6: {
    image: "SL0_089.jpg",
    label: "Image 6",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n5", yaw: -78, pitch: -8, viewYaw: 86, viewPitch: -7.6 }
    ],
    mapTop: 10.0,
    mapLeft: 64.3,
    hideOnMap: false
  },

  n7: {
    image: "SL0_090.jpg",
    label: "Image 7",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n8", yaw: 175, pitch: -4, viewYaw: 180, viewPitch: 0 },
      { id: "n5", yaw: -5, pitch: -6, viewYaw: -6, viewPitch: -7.6 },
      { id: "n18", yaw: 86, pitch: -1, viewYaw: 175, viewPitch: 2 }
    ],
    mapTop: 18.3,
    mapLeft: 50.7,
    hideOnMap: false
  },

  n8: {
    image: "SL0_091.jpg",
    label: "Image 8",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n7", yaw: -3, pitch: 0 },
      { id: "n9", yaw: 178, pitch: -6, viewYaw: 178, viewPitch: 0 }
    ],
    mapTop: 18.6,
    mapLeft: 35.9,
    hideOnMap: false
  },

  n9: {
    image: "SL0_092.jpg",
    label: "Image 9",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n8", yaw: -6, pitch: -8 },
      { id: "n10", yaw: 86, pitch: 0, viewYaw: 180, viewPitch: 0 },
      { id: "n25", yaw: 175, pitch: -2 }
    ],
    mapTop: 18.0,
    mapLeft: 25.9,
    hideOnMap: false
  },

  n10: {
    image: "SL0_093.jpg",
    label: "Image 10",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n9", yaw: -4, pitch: 0, viewYaw: -100, viewPitch: 0 },
      { id: "n21", yaw: 180, pitch: -5, viewYaw: -2, viewPitch: 10 }
    ],
    mapTop: 31.6,
    mapLeft: 25.2,
    hideOnMap: false
  },

  n11: {
    image: "SL0_094.jpg",
    label: "Image 11",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [

    ],
    mapTop: 50,
    mapLeft: 40,
    hideOnMap: true
  },

  n12: {
    image: "SL0_095.jpg",
    label: "Image 12",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n13", yaw: 180, pitch: -4, viewYaw: 180, viewPitch: 0 },
      { id: "n21", yaw: 90, pitch: -4, viewYaw: 180, viewPitch: 0 },
      { id: "n24", yaw: 0.4, pitch: 0.9, viewYaw: 130, viewPitch: 0 }
    ],
    mapTop: 60.2,
    mapLeft: 25.4,
    hideOnMap: false
  },

  n13: {
    image: "SL0_096.jpg",
    label: "Image 13",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n12", yaw: -6, pitch: 3 },
      { id: "n14", yaw: 176, pitch: -4, viewYaw: 180, viewPitch: 0 },
      { id: "n18", yaw: 84, pitch: 0 }
    ],
    mapTop: 61.1,
    mapLeft: 50.7,
    hideOnMap: false
  },

  n14: {
    image: "SL0_097.jpg",
    label: "Image 14",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n13", yaw: -4, pitch: 3 },
      { id: "n15", yaw: -90, pitch: 0, viewYaw: -180, viewPitch: 0 },
      { id: "n16", yaw: 180, pitch: -4, viewYaw: -90, viewPitch: 0 }
    ],
    mapTop: 61.4,
    mapLeft: 58.1,
    hideOnMap: false
  },

  n15: {
    image: "SL0_098.jpg",
    label: "Image 15",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n14", yaw: -2, pitch: 5, viewYaw: 88, viewPitch: 0 },
      { id: "n26", yaw: 148, pitch: -3, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 78.2,
    mapLeft: 59.6,
    hideOnMap: false
  },

  n16: {
    image: "SL0_107.jpg",
    label: "Image 16",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n17", yaw: 173, pitch: -3, viewYaw: 180, viewPitch: 0 },
      { id: "n14", yaw: 82, pitch: -5 }
    ],
    mapTop: 60.2,
    mapLeft: 70.7,
    hideOnMap: false
  },

  n17: {
    image: "SL0_108.jpg",
    label: "Image 17",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n16", yaw: -11, pitch: 4, viewYaw: 0, viewPitch: 0 },
      { id: "n4", yaw: 175, pitch: -5, viewYaw: -90, viewPitch: 4 }
    ],
    mapTop: 37.8,
    mapLeft: 71.1,
    hideOnMap: false
  },

  n18: {
    image: "SL0_109.jpg",
    label: "Image 18",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n19", yaw: -8, pitch: 2 },
      { id: "n13", yaw: 175, pitch: -3, viewYaw: -90, viewPitch: 0 },
      { id: "n7", yaw: -8, pitch: 2, viewYaw: -97, viewPitch: 6 }
    ],
    mapTop: 42.8,
    mapLeft: 50.7,
    hideOnMap: false
  },

  n19: {
    image: "SL0_111.jpg",
    label: "Image 19",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n18", yaw: -8, pitch: 2 }
    ],
    mapTop: 58,
    mapLeft: 48,
    hideOnMap: true
  },

  n20: {
    image: "SL0_112.jpg",
    label: "Image 20",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n24", yaw: -100, pitch: -25, viewYaw: 40, viewPitch: 2 },
      { id: "SL1_113", yaw: 174.0, pitch: 20.9 }
    ],
    mapTop: 57.5,
    mapLeft: 12.2,
    hideOnMap: false
  },

  n21: {
    image: "SL0_124.jpg",
    label: "Image 21",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n10", yaw: 180, pitch: -2 },
      { id: "n12", yaw: -2, pitch: 3, viewYaw: -90, viewPitch: 4 },
      { id: "n23", yaw: -78, pitch: 2, viewYaw: -40, viewPitch: -2 }
    ],
    mapTop: 44.5,
    mapLeft: 25.2,
    hideOnMap: false
  },

  n22: {
    image: "SL0_125.jpg",
    label: "Image 22",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n23", yaw: -58, pitch: -7, viewYaw: 143, viewPitch: 9 }
    ],
    mapTop: 39.5,
    mapLeft: 32.8,
    hideOnMap: false
  },

  n23: {
    image: "SL0_126.jpg",
    label: "Image 23",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n22", yaw: -43, pitch: 2, viewYaw: 90, viewPitch: 5 },
      { id: "n21", yaw: 106, pitch: -3 }
    ],
    mapTop: 39.2,
    mapLeft: 30.2,
    hideOnMap: false
  },

  n24: {
    image: "SL0_127.jpg",
    label: "Image 24",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n12", yaw: -51, pitch: -2, viewYaw: 180, viewPitch: 0 },
      { id: "n20", yaw: -156, pitch: -27, viewYaw: 180, viewPitch: 0 }
    ],
    mapTop: 60.8,
    mapLeft: 12.6,
    hideOnMap: false
  },

  n25: {
    image: "SL0_128.jpg",
    label: "Image 25",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n9", yaw: 177.6, pitch: -1.7 },
      { id: "SL1_052", yaw: 20, pitch: 0 }
    ],
    mapTop: 17.4,
    mapLeft: 5.6,
    hideOnMap: false
  },

  n26: {
    image: "SL0_129.jpg",
    label: "Image 26",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n27", yaw: -180, pitch: 18, viewYaw: 0, viewPitch: 0 },
      { id: "n15", yaw: 93, pitch: -6 }
    ],
    mapTop: 87.3,
    mapLeft: 61.1,
    hideOnMap: false
  },

  n27: {
    image: "SL0_130.jpg",
    label: "Image 27",
    description: "",
    defaultYaw: 0,
    defaultPitch: 0,
    neighbors: [
      { id: "n26", yaw: -120, pitch: 0 },
      { id: "SL1_131", yaw: 175.5, pitch: 13.0 }
    ],
    mapTop: 87.3,
    mapLeft: 65.9,
    hideOnMap: false
  }

};
